Blog.PL/Controllers/AccountController.cs
using Blog.BLL.Identity;
using Blog.Entity.Identity;
using Blog.Entity.ViewModel;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.PL.Controllers
{
    public class AccountController : BaseController
    {
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]    
        public ActionResult Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var usermanager = IdentityTools.NewUserManager();
            //var kullanici = usermanager.FindByName(model.Username);
            var kullanici = usermanager.FindByEmail(model.Email);
            if (kullanici != null)
            {
                ModelState.AddModelError("", "Bu email sistemde kayıtlı!");
                return View(model);
            }
            ApplicationUser user = new ApplicationUser();
            user.Name = model.Name;
            user.Surname = model.Surname;
            user.Email = model.Email;
            user.UserName = model.Username;

            var result = usermanager.Create(user, model.Password);

            if (result.Succeeded)
            {
                usermanager.AddToRole(user.Id, "Admin");
                return RedirectToAction("Login");
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error);
                }
            }
            return View(model);
        }
        public ActionResult Login(string returnUrl)
        {
            LoginViewModel model = new LoginViewModel() { returnUrl = returnUrl };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var usermanager = IdentityTools.NewUserManager();
            var kullanici = usermanager.FindByName(model.Username);
            if (kullanici == null)
            {
                ModelState.AddModelError("", "Böyle bir kullanıcı kayıtlı değil!");
                return View(model);
            }
            else
            {
                var authManager = HttpContext.GetOwinContext().Authentication;
                var identity = usermanager.CreateIdentity(kullanici, "ApplicationCookie");
                var authProperty = new AuthenticationProperties
                {
                    IsPersistent = model.RememberMe
                };
                authManager.SignIn(authProperty, identity);
                return Redirect(string.IsNullOrEmpty(model.returnUrl) ? "/" : model.returnUrl);
            }
        }
        [Authorize]
        public ActionResult LogOut()
        {
            HttpContext.GetOwinContext().Authentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

Blog.PL/Controllers/BaseController.cs
using Blog.BLL.Repository;
using Blog.DAL.Context;
using Blog.Entity.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.PL.Controllers
{
    public class BaseController : Controller
    {
        BlogContext ent = new BlogContext();

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            Repository<Category> repoC = new Repository<Category>(ent);
            ViewBag.Kategoriler = repoC.GetAll();

            Repository<Tag> repoT = new Repository<Tag>(ent);
            ViewBag.Etiketler = repoT.GetAll(null, t => t.OrderByDescending(x => x.Articles.Count)).Take(5);

            base.OnActionExecuting(filterContext);
        }

    }
}

Blog.PL/Controllers/HomeController.cs
using Blog.BLL.Repository;
using Blog.DAL.Context;
using Blog.Entity.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.PL.Controllers
{
    public class HomeController : BaseController
    {
        Repository<Article> repoM = new Repository<Article>(new BlogContext());
        Repository<Tag> repoT = new Repository<Tag>(new BlogContext());
        Repository<Category> repoC = new Repository<Category>(new BlogContext());
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SonEklenenMakaleler()
        {

            return PartialView(repoM.GetAll());
        }
        public ActionResult MakalelerByKategori(int Id)
        {
            return View(repoC.Get(k => k.Id == Id).Articles);
        }
        public ActionResult MakalelerByEtiket(int etiketId)
        {
            return View(repoT.Get(e => e.Id == etiketId).Articles);
        }
    }
}

Blog.PL/Controllers/MakaleController.cs
using Blog.BLL.Repository;
using Blog.DAL.Context;
using Blog.Entity.Entity;
using Blog.Entity.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.PL.Controllers
{
    public class MakaleController : BaseController
    {
        Repository<Article> repoM = new Repository<Article>(new BlogContext());
        Repository<Comment> repoC = new Repository<Comment>(new BlogContext());
        public ActionResult Index()
        {
            return View(repoM.GetAll(null, m => m.OrderByDescending(x => x.CreatedDate)).Take(4));
        }
        //[Authorize(Roles = "Admin, Yazar")]
        [Authorize]
        public ActionResult Ekle()
        {
            return View();
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Ekle(MakaleAddViewModel model)
        {
            if(model.PictureUpload != null)
            {
                //string name = Path.GetFileNameWithoutExtension(model.PictureUpload.FileName);
                //string ext = Path.GetExtension(model.PictureUpload.FileName);
                ////Resim upload edilecek.
                //name = name.Replace(" ", "");
                string filename = model.PictureUpload.FileName;
                string imagePath = Server.MapPath("/images/" + filename);
                model.PictureUpload.SaveAs(imagePath);
                //Makale eklenecek.
                Article yeni = new Article();
                yeni.Title = model.Title;
                yeni.Summary = model.Summary;
                yeni.Content = model.Content;
                yeni.Picture = filename;
                yeni.CategoryId = model.CategoryId;
                //yeni.UserId = HttpContext.User.Identity.GetUserId();
                yeni.UserId = "55b5fccd-fbd5-4f3a-9fc0-b4b0714cc96d";
                if (repoM.Add(yeni))
                    return RedirectToAction("Index");
                return View(model);
            }
            return View();
        }
        public ActionResult MakaleDetay(int Id)
        {
            MakaleDetayViewModel mdvm = new MakaleDetayViewModel();
            mdvm.Makale = repoM.GetById(Id);
            mdvm.Yorum = new Comment();
            mdvm.Yorumlar = mdvm.Makale.Comments.ToList();
            return View(mdvm);
        }
        [HttpPost]
        public ActionResult MakaleDetay(MakaleDetayViewModel model)
        {
            Comment yeniYorum = new Comment();
            yeniYorum.ArticleId = model.Makale.Id;
            yeniYorum.Content = model.Yorum.Content;
            //yeniYorum.UserId = HttpContext.User.Identity.GetUserId();
            yeniYorum.UserId = "55b5fccd-fbd5-4f3a-9fc0-b4b0714cc96d";
            if (repoC.Add(yeniYorum))
            {
                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

Blog.PL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Blog.PL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Blog.PL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@Html.Action("SonEklenenMakaleler", "Home")

Blog.PL/Views/Home/MakalelerByEtiket.cshtml
@model IEnumerable<Blog.Entity.Entity.Article>
@{
    ViewBag.Title = "MakalelerByEtiket";
}

@Html.Partial("SonEklenenMakaleler", Model)

Blog.PL/Views/Home/MakalelerByKategori.cshtml
@model IEnumerable<Blog.Entity.Entity.Article>
@{
    ViewBag.Title = "MakalelerByKategori";
}

@Html.Partial("SonEklenenMakaleler", Model)

Blog.PL/Views/Home/SonEklenenMakaleler.cshtml
@model IEnumerable<Blog.Entity.Entity.Article>

@if (Model.Count() == 0)
{
    <div class="masonry-grid-item">
        <p class="alert alert-info text-primary">Bu kategoride kayıtlı makale bulunmamaktadır.</p>
    </div>
}
else
{
    foreach (var item in Model)
    {
        <div class="masonry-grid-item col-md-6">
            <!-- blogpost start -->
            <article class="clearfix blogpost">
                <div class="overlay-container">
                    <img src="/images/@item.Picture" alt="">
                    <div class="overlay">
                        <div class="overlay-links">
                            <a href="/Makale/MakaleDetay/@item.Id"><i class="fa fa-link"></i></a>
                            <a href="/images/@item.Picture" class="popup-img-single" title='@item.Title'><i class="fa fa-search-plus"></i></a>
                        </div>
                    </div>
                </div>
                <div class="blogpost-body">
                    <div class="post-info">
                        <span class="day">@item.CreatedDate.Day</span>
                        <span class="month">
                            @item.CreatedDate.ToString("MMMM") @item.CreatedDate.Year
                            @*@string.Format("{0:y}", item.CreatedDate)*@
                            @*@item.CreatedDate. @item.CreatedDate.Year*@
                        </span>
                    </div>
                    <div class="blogpost-content">
                        <header>
                            <h2 class="title"><a href="blog-post.html">@item.Title</a></h2>
                            <div class="submitted"><i class="fa fa-user pr-5"></i> by <a href="#">@(item.User.Name + " " + item.User.Surname)</a></div>
                        </header>
                        @if (item.Summary.Length < 100)
                        {
                            <p>@Html.Raw(item.Summary)</p>
                        }
                        else
                        {
                            <p>@Html.Raw(item.Summary.Substring(0, 100))...</p>
                        }
                    </div>
                </div>
                <footer class="clearfix">
                    <ul class="links pull-left">
                        <li><i class="fa fa-comment-o pr-5"></i> <a href="#">@item.Comments.Count yorum</a> |</li>
                        <li><i class="fa fa-tags pr-5"></i> <a href="#">etiket @item.Tags.Count</a></li>
                    </ul>
                    <a class="pull-right link" href="blog-post.html"><span>Haber detayı</span></a>
                </footer>
            </article>
            <!-- blogpost end -->
        </div>
    }
}

Blog.PL/Views/Makale/Ekle.cshtml
@model Blog.Entity.ViewModel.MakaleAddViewModel

@{
    ViewBag.Title = "Ekle";
}
<script src="~/ckeditor/ckeditor.js"></script>
@using (Html.BeginForm("Ekle", "Makale", FormMethod.Post, new {encType="multipart/form-data" }))
{
<div class="form-horizontal">
    <h4>Yeni Makale</h4>
    <hr />
    <div class="form-group">
        @Html.Label("Kategori", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoryId", new SelectList(ViewBag.Kategoriler, "Id", "Name"), new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Makale Özeti", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Summary, 5, 83, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Makale İçeriği", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control ckeditor" } })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Resim Yükle", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.PictureUpload, new { type="file", name="PictureUpload", @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Kaydet" class="btn btn-default" />
        </div>
    </div>
</div>
}

<script>
    CKEDITOR.replace("Content", {
        uiColor: '#fc7f7f'
    });
</script>

Blog.PL/Views/Makale/Index.cshtml
@model IEnumerable<Blog.Entity.Entity.Article>

@if (Model.Count() == 0)
{
    <div class="masonry-grid-item">
        <p class="alert alert-info text-primary">Bu kategoride kayıtlı makale bulunmamaktadır.</p>
    </div>
}
else
{
    foreach (var item in Model)
    {
        <div class="masonry-grid-item col-md-6">
            <!-- blogpost start -->
            <article class="clearfix blogpost">
                <div class="overlay-container">
                    <img src="/images/@item.Picture" alt="">
                    <div class="overlay">
                        <div class="overlay-links">
                            <a href="/Makale/MakaleDetay/@item.Id"><i class="fa fa-link"></i></a>
                            <a href="/images/@item.Picture" class="popup-img-single" title='@item.Title'><i class="fa fa-search-plus"></i></a>
                        </div>
                    </div>
                </div>
                <div class="blogpost-body">
                    <div class="post-info">
                        <span class="day">@item.CreatedDate.Day</span>
                        <span class="month">
                            @item.CreatedDate.ToString("MMMM") @item.CreatedDate.Year
                            @*@string.Format("{0:y}", item.CreatedDate)*@
                            @*@item.CreatedDate. @item.CreatedDate.Year*@
                        </span>
                    </div>
                    <div class="blogpost-content">
                        <header>
                            <h2 class="title"><a href="blog-post.html">@item.Title</a></h2>
                            <div class="submitted"><i class="fa fa-user pr-5"></i> by <a href="#">@(item.User.Name + " " + item.User.Surname)</a></div>
                        </header>
                        @if (item.Summary.Length < 100)
                        {
                            <p>@Html.Raw(item.Summary)</p>
                        }
                        else
                        {
                            <p>@Html.Raw(item.Summary.Substring(0, 100))...</p>
                        }
                    </div>
                </div>
                <footer class="clearfix">
                    <ul class="links pull-left">
                        <li><i class="fa fa-comment-o pr-5"></i> <a href="#">@item.Comments.Count yorum</a> |</li>
                        <li><i class="fa fa-tags pr-5"></i> <a href="#">etiket @item.Tags.Count</a></li>
                    </ul>
                    <a class="pull-right link" href="blog-post.html"><span>Haber detayı</span></a>
                </footer>
            </article>
            <!-- blogpost end -->
        </div>
    }
}

Blog.PL/Views/Makale/MakaleDetay.cshtml
@model Blog.Entity.ViewModel.MakaleDetayViewModel
@{
    ViewBag.Title = "MakaleDetay";
}
<!-- page-intro start-->
<!-- ================ -->
@*<div class="page-intro">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ol class="breadcrumb">
                        <li><i class="fa fa-home pr-10"></i><a href="index.html">Anasayfa</a></li>
                        <li class="active">MakaleDetay</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>*@
<!-- page-intro end -->
<div class="container">
    <div class="row">
            <!-- main start -->
            <!-- ================ -->
        <div class="main col-md-8">
            <!-- page-title start -->
            <!-- ================ -->
            <h1 class="page-title">@Model.Makale.Title</h1>
            <!-- page-title end -->
            <!-- blogpost start -->
            <article class="clearfix blogpost full">
                <div class="blogpost-body">
                    <div class="side">
                        <div class="post-info">
                            <span class="day">@Model.Makale.CreatedDate.Day</span>
                            <span class="month">@Model.Makale.CreatedDate.ToString("MMMM") @Model.Makale.CreatedDate.Year</span>
                        </div>
                    </div>
                    <div class="blogpost-content">
                        <header>
                            <div class="submitted"><i class="fa fa-user pr-5"></i> by <a href="#">@(Model.Makale.User.Name + " " + Model.Makale.User.Surname)</a></div>
                        </header>
                        <div class="owl-carousel content-slider-with-controls">
                            <div class="overlay-container">
                                <img src="/images/@Model.Makale.Picture" alt="@Model.Makale.Title">
                                @*<a href="images/blog-1.jpg" class="popup-img overlay" title="image title"><i class="fa fa-search-plus"></i></a>*@
                            </div>
                            <div class="overlay-container">
                                <img src="/images/@Model.Makale.Picture" alt="@Model.Makale.Title">
                                @*<a href="images/blog-2.jpg" class="popup-img overlay" title="image title"><i class="fa fa-search-plus"></i></a>*@
                            </div>
                            <div class="overlay-container">
                                <img src="/images/@Model.Makale.Picture" alt="@Model.Makale.Title">
                                @*<a href="images/blog-3.jpg" class="popup-img overlay" title="image title"><i class="fa fa-search-plus"></i></a>*@
                            </div>
                        </div>
                        <p>
                            @Html.Raw(Model.Makale.Content)
                        </p>
                    </div>
                </div>
                <footer class="clearfix">
                    <ul class="links pull-left">
                        <li><i class="fa fa-comment-o pr-5"></i> <a href="#">@Model.Makale.Comments.Count yorum</a> |</li>
                        <li><i class="fa fa-tags pr-5"></i> <a href="#">etiket @Model.Makale.Tags.Count</a></li>
                    </ul>
                </footer>
            </article>
            <!-- blogpost end -->
            <!-- comments start -->
            <div class="comments">
                @if (Model.Makale.Comments.Count == 0)
                {
                    <h2 class="title">Henüz yorum eklenmemiştir.</h2>
                }
                else
                {
                    <h2 class="title">@Model.Makale.Comments.Count yorum eklenmiştir.</h2>
                    foreach (var yorum in Model.Yorumlar)
                    {
                        <!-- comment start -->
                        <div class="comment clearfix">
                            <div class="comment-avatar">
                                <img src="images/avatar.jpg" alt="avatar">
                            </div>
                            <div class="comment-content">
                                <h3>Yorum</h3>
                                <div class="comment-meta">By <a href="#">@(yorum.User.Name + " " + yorum.User.Surname)</a> | Today, 12:31</div>
                                <div class="comment-body clearfix">
                                    <p>@yorum.Content</p>
                                    <a href="blog-post.html" class="btn btn-gray more pull-right"><i class="fa fa-reply"></i> Cevapla</a>
                                </div>
                            </div>
                        </div>
                    }
                    <!-- comment end -->
                }
            </div>
            <!-- comments form start -->
            @using (Html.BeginForm())
            {
                <div class="comments-form">
                    <h2 class="title">Yorum Ekle</h2>
                    <div class="form-horizontal">
                        @Html.HiddenFor(model => model.Makale.Id)
                        <div class="form-group">
                            @Html.Label("Mesaj", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Yorum.Content, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Kaydet" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </div>
            }
                <!-- comments form end -->
            </div>
            <!-- main end -->
    </div>
</div>

Blog.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>